baseURL = "https://yakczar.com"
languageCode = "en-us"
title = "Zack's personal blog"
publishDir = "tmp"
RSSLink = "rss.xml"
enableGitInfo = true
pygmentsCodeFences=true 

[permalinks]
  post = "/:slug/"

[params]
  twitter = "yakczar"
  navigation = ["projects.md","about.md","contact.md"]
  analytics=true
  style="3"
