baseURL = "https://schollz.github.io"
languageCode = "en-us"
title = "schollz blog"
publishDir = "tmp"
RSSLink = "rss.xml"
enableGitInfo = true
pygmentsCodeFences=true 

[permalinks]
  post = "/:slug/"

[params]
  twitter = "yakczar"
  navigation = ["about.md","contact.md"]
